// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoFdLvq_UuVooLaueKdgbeyFtMaz1erAE',
    appId: '1:673434675221:web:042a362a0aebcd50ddc61c',
    messagingSenderId: '673434675221',
    projectId: 'ootdbe-57dfa',
    authDomain: 'ootdbe-57dfa.firebaseapp.com',
    storageBucket: 'ootdbe-57dfa.appspot.com',
    measurementId: 'G-Q4Q7TCQG0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5b2jk6wKBfEk9IOdbftqlSJJHvZ-un8Y',
    appId: '1:673434675221:android:1ca8ba249872f749ddc61c',
    messagingSenderId: '673434675221',
    projectId: 'ootdbe-57dfa',
    storageBucket: 'ootdbe-57dfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLbeOPy2PzzNhuNlVx-gbUxLTJZcR3Nak',
    appId: '1:673434675221:ios:412b3caa029dd561ddc61c',
    messagingSenderId: '673434675221',
    projectId: 'ootdbe-57dfa',
    storageBucket: 'ootdbe-57dfa.appspot.com',
    iosClientId: '673434675221-05f08i9h528573mp1d7gode9dca8ckn2.apps.googleusercontent.com',
    iosBundleId: 'com.ootdforyou.ootdforyou',
  );
}
